### ISSUE TITLE
Three undefined names in Python code

### ISSUE THREAD

**Issue by cclauss** [alexandreborges/malwoverview#10]
[flake8](http://flake8.pycqa.org) testing of https://github.com/alexandreborges/malwoverview on Python 3.8.3

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./malwoverview/malwoverview.py:1664:28: F821 undefined name 'polywarm'
                artifact = polywarm.download(DOWN_DIR, sha256)
                           ^
./malwoverview/malwoverview.py:5603:58: F821 undefined name 'package'
            print((mycolors.foreground.green + "%-08s" % package), end=' ')
                                                         ^
./malwoverview/malwoverview.py:6430:9: F821 undefined name 'alien_urls'
        alien_urls(urlalien,argx)
        ^
3     F821 undefined name 'polywarm'
3
```
https://flake8.pycqa.org/en/latest/user/error-codes.html

On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead, these tests are focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic language like Python, they result in the script halting/crashing on the user.
* F63 tests are usually about the confusion between identity and equality in Python.  Use ==/!= to compare str, bytes, and int literals is the classic case.  These are areas where __a == b__ is True but __a is b__ is False (or vice versa).  Python >= 3.8 will raise SyntaxWarnings on these instances.
* F7 tests logic errors and syntax errors in type hints
* F82 tests are almost always _undefined names_ which are usually a sign of a typo, missing imports, or code that has not been ported to Python 3.  These also would be compile-time errors in a compiled language but in Python, a __NameError__ is raised which will halt/crash the script on the user.

**Comment by alexandreborges** [comment]
Christian,

Good evening. How are you?

Thank you for all suggested fixes (code and typos). 

As I'd already submitted some small fixes to the repository before reading your message, so I've preferred including all of your suggestions manually and I've closed two PRs, but kept the third one open. 

I liked your suggestion about the os.sep, but I need to make some tests before accepting it. 

Finally, I've included your name as responsible for fixes of these version in the history changes. After validating the code change, so I'll include you as a contributor. 

Thank you for your time and suggestions, Christian. 

Have an excellent day. 

Alexandre.
