### ISSUE TITLE
call of hybrid-analysis API for SHA256 only

### ISSUE THREAD

**Issue by berloha** [alexandreborges/malwoverview#16]
Hello!
Why you used half of hybrid-analysis API with support SHA256 hash only? You can call first /search/hash API for all hash (MD5, SHA1, SHA256) to get SHA256 and use it for get /report/{SHA256}/summary.

See https://www.hybrid-analysis.com/docs/api/v2

**Comment by alexandreborges** [comment]
Dear berloha,

Good afternoon. How are you?

When I've implemented Hybrid Analysis APIs, I've preferred using only the native API support from HA. Anyway, I'll take your suggestion and I'll implement MD5 searching for HA. 

Thank you for the message and have an excellent weekend. 

Warm regards, 

Alexandre.

**Comment by berloha** [comment]
Thank you!
