### ISSUE TITLE
Failure to find .malwapi.conf file 

### ISSUE THREAD

**Issue by streetracer87** [alexandreborges/malwoverview#18]
I created a .malwapi.conf file in the home directory and now I get this :( 
![image](https://user-images.githubusercontent.com/54128683/94189647-01a04500-fe79-11ea-9d61-b9c8b98ee333.png)

_Originally posted by @streetracer87 in https://github.com/alexandreborges/malwoverview/issues/17#issuecomment-698537447_

**Comment by alexandreborges** [comment]
Streetracer87, 

Please, check if he .malwapi.conf is similar to the structure shown below: 

[VIRUSTOTAL]
VTAPI = ba5138382038422838108

[HYBRID-ANALYSIS]
HAAPI = 44ha3930147278ds3283...

[MALSHARE]
MALSHAREAPI = 7da373946aeee22727...

[HAUSSUBMIT]
HAUSSUBMITAPI = 3838daa393939... 

[POLYSWARM]
POLYAPI = 042828442aec.... 

[ALIENVAULT]
ALIENAPI = 8e24829df...

[MALPEDIA]
MALPEDIAAPI = 63838bdbdba87771aaa...

[VALHALLA]
VALHALLAAPI = 11111...

Have an excellent day. 

Alexandre.

**Comment by streetracer87** [comment]
Yay, 

It worked. Thanks Alex!
