### ISSUE TITLE
Suggestion - Add support for Palo Alto Network Wildfire

### ISSUE THREAD

**Issue by simonsigre** [alexandreborges/malwoverview#19]
A suggestion (can support) to see if we could get the Wildfire service (Palo Alto Networks) added.
There is a maintain python package; https://pypi.org/project/pan-python/

And also lots of doco; https://docs.paloaltonetworks.com/wildfire/u-v/wildfire-api/get-started-with-the-wildfire-api

e.g.

root@6842528c1fc7:~# panwfapi.py -K xxxxxxxxxxxxxxx  --hash 0508558D3B683EE7A041B067FA80B5D5B51C56C2335F27549A2021905E7D8DCE --report -x

**Comment by alexandreborges** [comment]
Dear simonsigre, 

Good evening. How are you? 

Thank you for your suggestion so much. I'll checkup it up. It seems being interesting. 

Have an excellent day.

Alexandre.
