### ISSUE TITLE
Suggestion - Add support for Any.Run

### ISSUE THREAD

**Issue by D3fD3c0y** [alexandreborges/malwoverview#20]
Hi, this seems to be an awesome project! Congrats!

Would it be possible to add Any.Run for the following features:
- Show hash information
- Check suspect files
- Check URLs
- Download malware samples
- Submit malware samples (still unsure if this is a great idea as any.run main interest is to interact with malware submitted, but still...)
- List last suspected URLs
- List last payloads

Regards

**Comment by alexandreborges** [comment]
D3fD3c0y , 

Good evening. How are you?

Previously Any.Run hadn't made their APIs available, so it wasn't possible. I'll check it again (I consider Any.Run an excellent service) and, if APIs are now available, so I'll implement it. 

Thank you for the suggestion. 

Have an excellent day. 

Best regards,

Alexandre.
