### ISSUE TITLE
Add support for uploading larger files

### ISSUE THREAD

**Issue by SteveBox0** [alexandreborges/malwoverview#31]
E.g.
https://developers.virustotal.com/reference/files-upload-url

**Comment by alexandreborges** [comment]
SteveBox0,

Good afternoon. How are you? 

Thank you for the suggestion and I'll add it into my list. I have a long list of implementations to do, and one of them is implement API v3 from VT, so soon I'll do it, I'll also implement this feature. 

Have an excellent day and great weekend. 

Alexandre.
