### ISSUE TITLE
Convert malwoverview to use a CLI framework

### ISSUE THREAD

**Issue by daddycocoaman** [alexandreborges/malwoverview#33]
Hi,

This is more of a question than an issue but malwoverview is just one massive file with what appears to be a bunch of different modules (VirusTotal, URLHaus, etc). Have you considered changing it to use a CLI framework such as Click or Typer to make it more modular and easier for people writing their own tools to use?

**Comment by alexandreborges** [comment]
Dear daddycocoaman, 

Good afternoon. How are you?

No, I haven't considered it yet. This time I'm fixing all provided options to shorten the set of available options, but your suggestion is welcome and I'll consider doing it in a near future. 

Thank you for reserving some time to leave this good idea and I hope you have an excellent day.

Alexandre.

**Comment by daddycocoaman** [comment]
Thanks for the quick response!
