### ISSUE TITLE
hi,bro, I found that this kind of error often occurs in use

### ISSUE THREAD

**Issue by diguoji** [alexandreborges/malwoverview#35]
![image](https://user-images.githubusercontent.com/22145301/188780728-075e0d49-fd96-4316-9ba1-98ee3dcf391f.png)
API configuration is ok，I want to solve this problem。

**Comment by alexandreborges** [comment]
Dear diguoji, 

Good morning. How are you?

Please, could you send me the hash and/or the sample?

Have an excellent day.

**Comment by alexandreborges** [comment]
> 

I've copied (by hand) the provided hash from your image and tested using -v 1 -V <sample>. Apparently, everything has worked well. Please, check whether your're using the most recent version of Malwoverview. 

![image](https://user-images.githubusercontent.com/13165245/188785506-55935602-d709-43f9-9906-2a34013eb16d.png)

**Comment by diguoji** [comment]
> 

Sorry I didn't see your reply until you copied the hash value. Is it because I used the API of the community vt? , I installed it about four or five days ago, it should be the latest

**Comment by alexandreborges** [comment]
No, I don't think so. To this example, I also used public VT API and my first impression was that you didn't received any response from VT. Please, double check the malwoverview's installation and respective packages.

**Comment by diguoji** [comment]
> No, I don't think so. To this example, I also used public VT API and my first impression was that you didn't received any response from VT. Please, double check the malwoverview's installation and respective packages.

Thanks for your reply, I am actively trying to take the time to fix it
