### ISSUE TITLE
Hi I am new to this. I am wondering what flags should I use to scan sha256 hashes.

### ISSUE THREAD

**Issue by Lester0142** [alexandreborges/malwoverview#40]
Thank you!

**Comment by alexandreborges** [comment]
> Thank you!

Lester, 

I am sorry for the delay in answering you, but I have been really busy in the last weeks. 

There are multiple ways to retrieve reports by using a SHA256 hash:

1. **malwoverview.py -v 8 -V <hash>**   (Virus Total)
2. **malwoverview.py -b 1 -B <hash>**   (Malware Bazaar)
3. **malwoverview.py -a 1 -A <hash>**   (Hybrid Analysis -- Windows binaries)
4. **malwoverview.py -j 2 -J <hash>**     (URL Haus)
5. **malwoverview.py -p 1 -P <hash>**   (Polyswarm)
6a. **malwoverview.py -x 1 -X <hash>**    (get the job ID)
6b. **malwoverview.py -x 2 -X <job ID>**  (Triage)

There is a **help provided by the malwoverview.py**, and **examples available on the web site**. 

Have a good weekend.
