### ISSUE TITLE
.malwapi.conf file is not in its expected location since v5.4.3

### ISSUE THREAD

**Issue by digitalsleuth** [alexandreborges/malwoverview#43]
When installing malwoverview, the .malwapi.conf file has typically been placed in `lib/python3.8/site-packages/root/.malwapi.conf`, however since v5.4.3, it's now located in `lib/python3.8/site-packages/home/aborges/.malwapi.conf`

This behavior is identical for 5.4.3 and 5.4.4, but does not exist in 5.4.2 or earlier. I believe this may have occurred during build time, where `sudo` may have been used previously, but was not for these builds.

**Comment by alexandreborges** [comment]
Dear DigitalSleuth, 

Good afternoon. I've just submitted the new release (version 5.4.5) to the GitHub and also to Pypi website. Please, when it's possible, check if the issue has been fixed.

Thank you for the message and have an excellent day.

Alexandre.

**Comment by digitalsleuth** [comment]
Hi @alexandreborges , this works perfectly. Thank you kindly!
