### ISSUE TITLE
documentation in readme?

### ISSUE THREAD

**Issue by psifertex** [alexandreborges/malwoverview#51]
It would be great if the documentation from --help was included in the readme

**Comment by alexandreborges** [comment]
Dear psifertex

Good afternoon. How are you?

Previously there was exactly the help content in the README.md, and surprisingly many professionals didn't use it. I'll think about re-including it in the README.md.

Thank you for the suggestion and have a good day.

Alexandre.

**Comment by psifertex** [comment]
I'm well,  thanks. I hope you are too. 

Feel free to close the issue if it's not something you plan to add, I just wanted to raise the suggestion.

**Comment by alexandreborges** [comment]
Jordan, 

Good morning. As I had promised, documentation (help) has been included to README.md.

Have an excellent day.

Alexandre.

**Comment by alexandreborges** [comment]
I am closing this issue because it was solved.
