### ISSUE TITLE
Suggestion for switching to python3

### ISSUE THREAD

**Issue by jairtontf** [alexandreborges/malwoverview#6]
Python 2 will not be maintained past 2020 then I suggest swap for python 3.

This site: https://pythonconverter.com/ can help a lot!

**Comment by alexandreborges** [comment]
Jairton,

Good evening. How are you?

This migration is planned to be executed soon I have enough time (likely in December). Anyway, the support will end, but nothing will stop working. :) 

Thank you for the suggestion so much. I'll check it. 

Have an amazing day.

Alexandre.
