### ISSUE TITLE
configmalw.py is not used in version 2.0.8

### ISSUE THREAD

**Issue by mkilijanek** [alexandreborges/malwoverview#7]
Config file appears not being used in pip version of malwoverview (2.0.8), which forces end user to provide API keys directly in malwoverview to work with tool. (In my case it worked as temporary workaround)
![2019-12-30_13-32](https://user-images.githubusercontent.com/10347676/71582189-50e36000-2b09-11ea-8132-5b106be92bad.png)

**Comment by mkilijanek** [comment]
Version taken from contents of file:
![2019-12-30_13-38](https://user-images.githubusercontent.com/10347676/71582390-57260c00-2b0a-11ea-865c-d1c4b7660dd9.png)

**Comment by alexandreborges** [comment]
Kili, 

Good morning. How are you?

I've just replied you on Twitter and, according to my test here (just now), I haven't faced any problem. Please, could you confirm whether you edited the **configmalw.py** in **/usr/local/lib/python3.8/dist-packages/malwoverview/conf/** (or similar) directory?

Have an excellent day. 

![image](https://user-images.githubusercontent.com/13165245/71583339-c5f46c80-2aec-11ea-81be-cb6fb96961cd.png)

**Comment by mkilijanek** [comment]
My OS: Fedora 31 (Linux kili 5.3.16-300.fc31.x86_64; Security Spin + KDE Plasma; RPM Fusion enabled)

(malloverview) ➜  bin pip --version
pip 19.3.1 from /home/kili/VENV/malloverview/lib/python3.7/site-packages/pip (python 3.7)
(malloverview) ➜  bin python3 --version
Python 3.7.5

Steps I performed: 
1. Create directory for malwoverview.
2. Make virtualenv in directory from previous step.
3. source {malwoverview_dir}/bin/activate
4. cd {malwoverview_dir}
5. pip install malwoverview
6. cd bin
7. Edit configmalw.py providing all API keys (I used literally all variables)
8. ./malwoverview
9. Observe if your API keys are recognized.

I think result might differ between Linux distros :(

**Comment by mkilijanek** [comment]
Config file location is in bin directory of Virtualenv.
No directory structure as you described is observed.

**Comment by alexandreborges** [comment]
Dear mkilijanek, 

The problem is not the the different of OS versions, but the final directory structure. In a nutshell, you were using the "wrong" configmalw.py because the installation has been "virtualized and sourced".

Please, try to follow the same steps below and let me know whether everything goes right.  

Have an excellent day.

Alexandre.

![image](https://user-images.githubusercontent.com/13165245/71596261-9ca00480-2b1d-11ea-9437-e03929e0fe32.png)

**Comment by alexandreborges** [comment]
Due to no further comments, I'm closing the issue.
